### ISSUE TITLE
Does this plugin work in Totara

### ISSUE THREAD

**Issue by ThomasTLH** [moodleuulm/moodle-local_profiletheme#12]
Hi, I was trying to configure this plugin for Totara but it doesn't seem to work. Can you tell me if this should work in Totara as well or is there another way to get it to work inside of Totara? I m checking this for a client so if possible please react. Thx!

**Comment by abias** [comment]
Hi @ThomasTLH ,

thanks for asking.

This plugin is only developed for Moodle and there isn't any testing done on Totara. I am especially hesitant to promise any Totara compatibility for Moodle plugins since Totara diverged away from Moodle after Totara 2.9.

In Totara, there are audiences which lets you group users based on their user profile field values. If I would have to research it, I would check if there is any way to assign a theme to an audience in Totara core before trying to install this plugin.

Additionally, this plugin has become partly obsolete after Moodle 3.5 when Cohort themes were introduced into Moodle core (see https://docs.moodle.org/35/en/Cohort_sync#Cohort_themes). Perhaps Totara has adopted this change as well and you can use it directly.

Hope this helps in any way.

Cheers,
Alex
